---
title: "warncleaning"
output: html_document
date: "2023-02-25"
author: "Yash Gupta"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
```

## Data Cleaning

The code below reads in the CSV of the WARN database that can be found at https://layoffdata.com/data/.

```{r}
layoff = read_csv('data/warn.csv')
```


```{r}

layoff = layoff %>%
  rename(state = "State", company = "Company", city = "City", laidoff = "Number of Workers", warn_date = "WARN Received Date", eff_date = "Effective Date", layoff_type = "Closure/Layoff")

layoff = layoff %>% 
  mdy(!is.na(layoff$warn_date)) %>%
  mdy(!is.na(layoff$eff_date))
  
# na_check = layoff %>% 
#   rename(state = "State", company = "Company", city = "City", laidoff = "Number of Workers", warn_date = "WARN Received Date", eff_date = "Effective Date", layoff_type = "Closure/Layoff") %>%
#   group_by(state)

# layoff_refined = layoff %>%
#   select(state, laidoff) %>%
#   group_by(state, city) %>%
#   summarize(total_laidoff = sum(!is.na(laidoff)))



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
